site_name: eggolib Documentation

nav:
  - Home: index.md
  - General Types:
    - Data Types: types/data_types.md
    - Power Types: types/power_types.md
  - Action Types:
    - Block Action Types: types/block_action_types.md
    - Entity Action Types: types/entity_action_types.md
    - Meta Action Types: types/meta_action_types.md
  - Condition Types:
    - Block Condition Types: types/block_condition_types.md
    - Damage Condition Types: types/damage_condition_types.md
    - Entity Condition Types: types/entity_condition_types.md
    - Item Condition Types: types/item_condition_types.md
    - Meta Condition Types: types/meta_condition_types.md
  - Miscellaneous:
    - Class Data Registries: misc/class_data_registries.md

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - search.share

plugins:
  - search
  - mike

markdown_extensions:
  - toc:
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - meta
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
